# Console / UART
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y

# GPIO
CONFIG_GPIO=y
CONFIG_XHEEP_GPIO=y

# Threading
CONFIG_MULTITHREADING=y

# Debug / Misc
CONFIG_ASSERT=y

# Platform Deployment (y: PYNQ-Z2, n: Verilator)
CONFIG_XHEEP_FPGA_PYNQZ2=y
