# Console / UART
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# GPIO
CONFIG_GPIO=y
CONFIG_XHEEP_GPIO=y

# Interrupt Controllers
CONFIG_MULTI_LEVEL_INTERRUPTS=y
CONFIG_2ND_LEVEL_INTERRUPTS=y
CONFIG_2ND_LVL_ISR_TBL_OFFSET=32
CONFIG_DYNAMIC_INTERRUPTS=y
CONFIG_PLIC=n
CONFIG_XHEEP_PLIC=y
CONFIG_INTC_INIT_PRIORITY=40

# Debug / Misc
CONFIG_ASSERT=y
CONFIG_DEBUG=y
