# Console / UART
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# Counter driver
CONFIG_COUNTER=y

# Debug / Misc
CONFIG_ASSERT=y
CONFIG_DEBUG=y
